apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploiement-serveur-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: image-serveur-mongoDB:latest
        ports:
        - containerPort: 27017